[package]
name = "tcp_server"
version = "0.1.0"
edition = "2024"

[dependencies]
pnet_base = { version = "0.35.0", default-features = false }
pnet_macros_support = { version = "0.35.0" }
pnet_macros = { version = "0.35.0" }
crc = "3.2.1"
